import {
	type ApiCacheKey,
	CacheKey,
	DAYS_SHORT,
	DAY_NAMES,
	FediverseCacheKey,
	LoadAction,
	LogAction,
	MINUTES_IN_DAY,
	MINUTES_IN_HOUR,
	MONTHS,
	MONTHS_SHORT,
	NonScoreWeightName,
	SECONDS_IN_HOUR,
	TagPostsCategory,
} from "./enums";
/**
 * @fileoverview Centralized location for non-user configurable settings.
 */
import {
	isDebugMode,
	isLoadTest,
	isQuickMode,
} from "./helpers/environment_helpers";
import { optionalSuffix, suffixedInt } from "./helpers/string_helpers";
import { timeString } from "./helpers/time_helpers";
import type { NonScoreWeightInfoDict, Optional } from "./types";

// Number of notifications, replies, etc. to pull in initial load. KEY BOTTLENECK on RecentUserPosts
export const MIN_RECORDS_FOR_FEATURE_SCORING = 320;
export const MAX_ENDPOINT_RECORDS_TO_PULL = 5_000;

// Locale
const DEFAULT_LOCALE = "en-CA";
const DEFAULT_LANGUAGE = DEFAULT_LOCALE.split("-")[0];
const DEFAULT_COUNTRY = DEFAULT_LOCALE.split("-")[1];
const LOCALE_REGEX = /^[a-z]{2}(-[A-Za-z]{2})?$/;

const LOG_PREFIX = "[Config]";

type ApiRequestDefaults = {
	initialMaxRecords?: number; // How many records to pull in the initial bootstrap
	canBeDisabledOnGoToSocial?: boolean; // If true, this endpoint is enabled on GoToSocial servers
	limit?: number; // Max per page is usually 40
	lookbackForUpdatesMinutes?: number; // How long to look back for updates (edits, increased reblogs, etc.)
	maxCacheRecords?: number;
	minutesUntilStale?: number; // How long until the data is considered stale
	skipCache?: boolean; // If true, skip the cache and always make a request
	supportsMinMaxId?: boolean; // True if the endpoint supports min/maxId
};

type ApiDataConfig = Record<ApiCacheKey, ApiRequestDefaults>;

// See Config object for comments explaining these and other values
interface ApiConfig {
	backgroundLoadIntervalMinutes: number;
	backgroundLoadSleepBetweenRequestsMS: number;
	data: Readonly<ApiDataConfig>;
	daysBeforeFullCacheRefresh: number; // How many days before the cache is considered stale and needs to be refreshed completely
	defaultRecordsPerPage: number;
	errorMsgs: {
		accessTokenRevoked: string;
		goToSocialHashtagTimeline: (s: string) => string;
		rateLimitError: string;
		rateLimitWarning: string;
	};
	maxConcurrentHashtagRequests: number;
	maxRecordsForFeatureScoring: number;
	maxSecondsPerPage: number;
	minutesUntilStaleDefault: number;
	mutexWarnSeconds: number;
	timeoutMS: number;
}

type FediverseConfig = {
	numServersToCheck: number;
};

type LoadingStatusMsgs = Omit<
	Record<LoadAction, string>,
	LoadAction.FEED_UPDATE
>;
type TriggerLoadMsgFxn = {
	[LoadAction.FEED_UPDATE]: (
		arr: Array<unknown>,
		since: Optional<Date>,
	) => string;
};

type LocaleConfig = {
	country: string;
	defaultLanguage: string;
	language: string;
	locale: string;
	messages: LoadingStatusMsgs & TriggerLoadMsgFxn; // TRIGGER_FEED_UPDATE is a fxn, everything else is a string
};

interface ParticipatedTagsConfig extends TagPostsConfig {
	minPctToCountBoosts: number;
}

type ScoringConfig = {
	diversityScorerMinTrendingTagPostsForPenalty: number;
	diversityScorerBoostMultiplier: number; // How much to multiply the diversity score of a post with retweets by
	excessiveTags: number;
	excessiveTagsPenalty: number;
	nonScoreWeightMinValue: number;
	nonScoreWeightsConfig: Readonly<NonScoreWeightInfoDict>;
	scoringBatchSize: number;
	timeDecayExponent: number;
};

export interface TagPostsConfig {
	invalidTags?: string[];
	maxPosts: number;
	numTags: number;
	numPostsPerTag: number;
}

type PostsConfig = {
	batchCompleteSize: number;
	batchCompleteSleepBetweenMS: number;
	completeAfterMinutes: number;
	filterUpdateBatchSize: number; // How many new Posts before calling updateFilterOptions()
	maxAgeInDays: number;
	maxTimelineLength: number;
	minToSkipFilterUpdates: number;
	minCharsForLanguageDetect: number;
	saveChangesIntervalSeconds: number;
	tagOnlyStrings: Set<string>;
	truncateFullTimelineToLength: number;
};

interface TrendingTagsConfig extends TagPostsConfig {
	numTagsPerServer: number;
}

type TrendingPostsConfig = {
	numTrendingPostsPerServer: number;
};

type TrendingConfig = {
	daysToCountTrendingData: number;
	tags: Readonly<TrendingTagsConfig>;
	posts: Readonly<TrendingPostsConfig>;
};

// See Config for comments explaining these values
interface ConfigType {
	api: ApiConfig;
	favouritedTags: Readonly<TagPostsConfig>;
	fediverse: Readonly<FediverseConfig>;
	locale: Readonly<LocaleConfig>;
	participatedTags: Readonly<ParticipatedTagsConfig>;
	scoring: Readonly<ScoringConfig>;
	posts: Readonly<PostsConfig>;
	trending: Readonly<TrendingConfig>;
}

/**
 * Centralized application configuration class for non-user configurable settings.
 *
 * Provides strongly-typed, centralized access to all core settings for API requests,
 * locale, scoring, trending, and fediverse-wide data. It includes logic for environment-specific overrides
 * (debug, quick load, load test), validation of config values, and locale/language management.
 *
 * @class
 * @implements {ConfigType}
 * @property {ApiConfig} api - API request and caching configuration.
 * @property {TagPostsConfig} favouritedTags - Settings for favourited tags and related post fetching.
 * @property {FediverseConfig} fediverse - Fediverse-wide server and trending configuration.
 * @property {LocaleConfig} locale - Locale, language, and country settings.
 * @property {ParticipatedTagsConfig} participatedTags - Settings for user's participated tags.
 * @property {ScoringConfig} scoring - Scoring and weighting configuration for posts and tags.
 * @property {PostsConfig} posts - Timeline and post cache configuration.
 * @property {TrendingConfig} trending - Trending data configuration for links, tags, and posts.
 */
class Config implements ConfigType {
	api = {
		// How long to wait between API requests during backgrund load (actually a random number between 0 and this value)
		backgroundLoadSleepBetweenRequestsMS: 1_200,
		backgroundLoadIntervalMinutes: 10, // Time between background polling for additional user data after initial load
		daysBeforeFullCacheRefresh: 21, // Days before the cache is considered stale and needs to be refreshed completely  // TODO: currently unused
		defaultRecordsPerPage: 40, // Max per page is usually 40: https://docs.joinmastodon.org/methods/timelines/#request-2
		errorMsgs: {
			accessTokenRevoked: "The access token was revoked", // Error messsage thrown by masto.js
			goToSocialHashtagTimeline: (s: string) =>
				`GoToSocial servers don't enable ${s} by default, check if yours does.`,
			rateLimitError: "Too many requests", // MastoHttpError: Too many requests
			rateLimitWarning:
				"Your Mastodon server is complaining about too many requests coming too quickly. Wait a bit and try again later.",
		},
		maxConcurrentHashtagRequests: 15, // How many post requests to make in parallel to the search and hashtag timeline endpoints
		maxRecordsForFeatureScoring: 1_500, // number of notifications, replies, etc. to pull slowly in background for scoring
		maxSecondsPerPage: 60, // If loading a single page of results takes longer than this, just give up
		minutesUntilStaleDefault: 10, // Default how long to wait before considering data stale
		mutexWarnSeconds: 10, // How long to wait before warning about a mutex lock
		timeoutMS: 2_500, // Timeout for API calls
		data: {
			// See comments on ApiDataConfig for explanations of these values
			[CacheKey.BLOCKED_ACCOUNTS]: {
				initialMaxRecords: MAX_ENDPOINT_RECORDS_TO_PULL,
				minutesUntilStale: 12 * MINUTES_IN_HOUR,
			},
			[CacheKey.BLOCKED_DOMAINS]: {
				canBeDisabledOnGoToSocial: true,
				initialMaxRecords: MAX_ENDPOINT_RECORDS_TO_PULL,
				minutesUntilStale: MINUTES_IN_DAY,
			},
			[CacheKey.FAVOURITED_POSTS]: {
				initialMaxRecords: Math.floor(MIN_RECORDS_FOR_FEATURE_SCORING / 2), // Seems to be the biggest bottleneck
				minutesUntilStale: 12 * MINUTES_IN_HOUR,
			},
			[CacheKey.FOLLOWED_ACCOUNTS]: {
				initialMaxRecords: 1_600,
				limit: 80,
				minutesUntilStale: 12 * MINUTES_IN_HOUR,
			},
			[CacheKey.FOLLOWED_TAGS]: {
				initialMaxRecords: MAX_ENDPOINT_RECORDS_TO_PULL,
				limit: 100,
				minutesUntilStale: 12 * MINUTES_IN_HOUR,
			},
			[CacheKey.FOLLOWERS]: {
				initialMaxRecords: 1_600,
				limit: 80,
				minutesUntilStale: 24 * MINUTES_IN_HOUR,
			},
			[CacheKey.HASHTAG_POSTS]: {
				// hashtag timeline posts are not cached as a group, they're pulled in small amounts and used
				// to create other sets of posts from a lot of small requests, e.g. TRENDING_TAG_POSTS or PARTICIPATED_TAG_POSTS
				canBeDisabledOnGoToSocial: true,
			},
			[CacheKey.HOME_TIMELINE_POSTS]: {
				initialMaxRecords: 800,
				lookbackForUpdatesMinutes: 180, // How far before the most recent post we already have to look back for updates (edits, increased reblogs, etc.)
				supportsMinMaxId: true,
			},
			[CacheKey.INSTANCE_INFO]: {
				minutesUntilStale: 30 * MINUTES_IN_DAY,
			},
			[CacheKey.MUTED_ACCOUNTS]: {
				initialMaxRecords: MAX_ENDPOINT_RECORDS_TO_PULL,
				minutesUntilStale: 12 * MINUTES_IN_HOUR,
			},
			[CacheKey.NOTIFICATIONS]: {
				initialMaxRecords: MIN_RECORDS_FOR_FEATURE_SCORING,
				limit: 80,
				maxCacheRecords: 10_000,
				minutesUntilStale: 6 * MINUTES_IN_HOUR,
				supportsMinMaxId: true,
			},
			[CacheKey.RECENT_USER_POSTS]: {
				initialMaxRecords: MIN_RECORDS_FOR_FEATURE_SCORING,
				minutesUntilStale: 2 * MINUTES_IN_HOUR,
				supportsMinMaxId: true,
			},
			[CacheKey.SERVER_SIDE_FILTERS]: {
				initialMaxRecords: MAX_ENDPOINT_RECORDS_TO_PULL,
				minutesUntilStale: 4 * MINUTES_IN_HOUR,
			},
			[FediverseCacheKey.POPULAR_SERVERS]: {
				minutesUntilStale: 5 * MINUTES_IN_DAY,
			},
			[FediverseCacheKey.TRENDING_TAGS]: {
				minutesUntilStale: 6 * MINUTES_IN_HOUR,
			},
			[FediverseCacheKey.TRENDING_POSTS]: {
				minutesUntilStale: 4 * MINUTES_IN_HOUR,
			},
			[TagPostsCategory.FAVOURITED]: {
				minutesUntilStale: 60,
			},
			[TagPostsCategory.PARTICIPATED]: {
				minutesUntilStale: 20,
			},
			[TagPostsCategory.TRENDING]: {
				minutesUntilStale: 15,
			},
		} as ApiDataConfig,
	};

	favouritedTags = {
		maxParticipations: 3, // Remove tags that have been used in more than this many posts by the user
		maxPosts: 100, // How many posts to pull for each tag
		numTags: 15, // How many tags to pull posts for
		numPostsPerTag: 5, // How many posts to pull for each tag
	};

	fediverse = {
		numServersToCheck: 30, // NUM_SERVERS_TO_CHECK
	};

	locale = {
		country: DEFAULT_COUNTRY,
		defaultLanguage: DEFAULT_LANGUAGE,
		language: DEFAULT_LANGUAGE,
		locale: DEFAULT_LOCALE,
		messages: {
			// FEED_UPDATE is a fxn, everything else is a string
			[LogAction.FINISH_FEED_UPDATE]: `Finalizing scores`,
			[LogAction.INITIAL_LOADING_STATUS]: "Ready to load",
			[LoadAction.FEED_UPDATE]: (
				timeline: Array<unknown>,
				since: Optional<Date>,
			) => {
				if (timeline.length == 0) {
					return `Loading more posts (retrieved ${timeline.length.toLocaleString()} posts so far)`;
				} else {
					return (
						`Loading new posts` +
						optionalSuffix(since, `since ${timeString(since)}`)
					);
				}
			},
			[LoadAction.GET_CONVERSATION]: `Loading conversation`,
			[LoadAction.GET_MOAR_DATA]: `Fetching more data for the algorithm`,
			[LoadAction.IS_BUSY]:
				"Load in progress (consider using the setTimelineInApp() callback instead)",
			[LoadAction.PULL_ALL_USER_DATA]: `Pulling your historical data`,
			[LoadAction.REFRESH_MUTED_ACCOUNTS]: `Refreshing muted accounts`,
			[LoadAction.RESET]: `Resetting state`,
			[LoadAction.TIMELINE_BACKFILL]: `Loading older home timeline posts`,
		},
	};

	participatedTags = {
		invalidTags: ["eupol", "news", "uspol", "uspolitics"],
		maxPosts: 200, // How many total posts to include for the user's most participated tags
		minPctToCountBoosts: 0.75, // Minimum percentage of retweets to count them as "participation"
		numTags: 30, // Pull posts for this many of the user's most participated tags
		numPostsPerTag: 10, // How many posts to pull for each participated tag
	};

	scoring = {
		excessiveTags: 25, // Posts with more than this many tags will be penalized
		excessiveTagsPenalty: 0.1, // Multiplier to penalize posts with excessive tags
		diversityScorerMinTrendingTagPostsForPenalty: 9, // Min number of posts w/a trending tag before DiversityFeedScorer applies a penalty
		diversityScorerBoostMultiplier: 4, // How much to multiply the diversity score of a post with retweets by
		nonScoreWeightMinValue: 0.001, // Min value for non-score weights (trending, time decay, etc.)
		nonScoreWeightsConfig: {
			// Factor in an exponential function that gives a value between 0 and 1. See Scorer class for details.
			[NonScoreWeightName.TIME_DECAY]: {
				description: "Higher values favour recent posts more",
			},
			// Trending data has a lot of reblogs, likes, replies, etc. giving disproportionately high scores.
			// To adjust for this we multiply those scores by the TRENDING weighting value.
			[NonScoreWeightName.TRENDING]: {
				description: "Multiplier applied to trending posts, tags, and links",
			},
			// If this value is 2 then square root scores, if it's 3 then cube root scores, etc.
			[NonScoreWeightName.OUTLIER_DAMPENER]: {
				description: "Dampens the effect of outlier scores",
			},
		},
		scoringBatchSize: 100, // How many posts to score at once
		timeDecayExponent: 1.2, // Exponent for the time decay function (higher = more recent posts are favoured)
	};

	posts = {
		batchCompleteSize: 25, // How many posts call completeToot() on at once
		batchCompleteSleepBetweenMS: 210, // How long to wait between batches of Post.completeProperties() calls
		completeAfterMinutes: MINUTES_IN_DAY, // Posts younger than this will periodically have their derived fields reevaluated by Post.completeToot()
		filterUpdateBatchSize: 240, // How many new Posts before calling updateFilterOptions()
		maxAgeInDays: 1, // How long to keep posts in the cache before removing them
		maxContentPreviewChars: 110, // How many characters to show in a Post preview
		maxTimelineLength: 3_000, // Max posts to keep in browser storage. Larger cache doesn't seem to impact performance much
		minCharsForLanguageDetect: 8, // Min number of characters in a post before we try to detect its language
		minToSkipFilterUpdates: 300, // Min timeline posts before we start getting choosy about calling updateFilterOptions()
		saveChangesIntervalSeconds: 5, // How often to check for updates to posts' numTimesShown
		truncateFullTimelineToLength: 2_000, // If on startup the timeline is full, truncate it to this length
		tagOnlyStrings: new Set<string>([
			// These strings can only be matched as tags, not as content
			...DAY_NAMES.map((m) => m.toLowerCase()),
			...DAYS_SHORT.map((m) => m.toLowerCase()),
			...MONTHS.map((m) => m.toLowerCase()),
			...MONTHS_SHORT.map((m) => m.toLowerCase()),
			...Array.from({ length: 31 }, (_, i) => suffixedInt(i)),
			"ab",
			"abc",
			"abandon",
			"abandoned",
			"abandoning",
			"about",
			"abstract",
			"access",
			"accessed",
			"accessing",
			"accessory",
			"accessories",
			"accident",
			"accidents",
			"account",
			"accountability",
			"accounts",
			"accuracy",
			"achieve",
			"achieved",
			"achieving",
			"across",
			"act",
			"acted",
			"acting",
			"action",
			"actions",
			"activities",
			"activity",
			"activitypub",
			"actor",
			"actu", // French
			"actual",
			"actualite", // French
			"actualites", // French
			"adam",
			"add",
			"address",
			"admin",
			"administration",
			"administrations",
			"administer",
			"administered",
			"administering",
			"administers",
			"adopt",
			"adopted",
			"adopting",
			"advance",
			"advanced",
			"advances",
			"advancing",
			"advertise",
			"advise",
			"advised",
			"advises",
			"advising",
			"advisory",
			"affect",
			"affected",
			"affecting",
			"affects",
			"affiliated",
			"affiliating",
			"affinities",
			"affinity",
			"after",
			"afternoon",
			"afternoons",
			"afterward",
			"afterwards",
			"again",
			"against",
			"age",
			"agency",
			"agenda",
			"agendas",
			"agent",
			"agents",
			"aggression",
			"ago",
			"agree",
			"agreeable",
			"agreeing",
			"agreement",
			"agreements",
			"agrees",
			"agreed",
			"ahead",
			"aid",
			"air",
			"aktuel", // German
			"aktuell", // German
			"alex",
			"alienvault",
			"all",
			"allies",
			"ally",
			"also",
			"alt",
			"alternative",
			"alternatives",
			"am",
			"amaze",
			"amazed",
			"amazing",
			"america",
			"americaine", // French
			"american",
			"americans",
			"americas",
			"amid",
			"amidst",
			"among",
			"amongst",
			"an",
			"analysis",
			"and",
			"andrew",
			"andy",
			"angeles",
			"anger",
			"angrier",
			"angry",
			"animate",
			"animated",
			"animates",
			"ann",
			"anna",
			"announce",
			"announced",
			"announcement",
			"announcements",
			"announcing",
			"ano", // Spanish
			"anos", // Spanish
			"another",
			"answer",
			"answered",
			"answering",
			"answers",
			"anti",
			"any",
			"app",
			"application",
			"applications",
			"approach",
			"approached",
			"approaches",
			"approaching",
			"apps",
			"ar",
			"archive", // archive.org links
			"are",
			"area",
			"areas",
			"armes", // French
			"arrive",
			"article",
			"articles",
			"articulate",
			"articulated",
			"articulating",
			"artificial",
			"artificially",
			"arts",
			"as",
			"ask",
			"asked",
			"asking",
			"asp", // ASP.NET pages
			"aspx", // ASP.NET pages
			"ass",
			"asses",
			"assess",
			"assessed",
			"assessing",
			"asset",
			"asshole",
			"assholes",
			"associate",
			"associated",
			"associates",
			"association",
			"at",
			"ate",
			"attempt",
			"attempted",
			"attempting",
			"attempts",
			"attend",
			"attended",
			"attendee",
			"attendees",
			"attending",
			"attends",
			"attention",
			"au", // Country code for Australia
			"auch", // German
			"audio",
			"aus", // German
			"author",
			"authored",
			"authors",
			"authority",
			"authorities",
			"auto",
			"autumn",
			"avoid",
			"aware",
			"awareness",
			"away",
			"ayuda", // Spanish
			"ba",
			"back",
			"backed",
			"background",
			"backs",
			"bad",
			"badly",
			"bag",
			"bags",
			"bahn", // German
			"baked",
			"ball",
			"balls",
			"bank",
			"banken", // German?
			"bar",
			"barred",
			"barring",
			"bars",
			"bas", // Indian English
			"base",
			"based",
			"basic",
			"bay",
			"bc", // "because"
			"be",
			"bear",
			"bearing",
			"beast",
			"beat",
			"beats",
			"beautiful",
			"beauty",
			"before",
			"behavior",
			"belief",
			"beliefs",
			"believe",
			"believed",
			"believes",
			"believing",
			"benefit",
			"benefits",
			"benjamin",
			"best",
			"bet",
			"beta",
			"betray",
			"betrayed",
			"betraying",
			"betrays",
			"better",
			"betting",
			"between",
			"beyond",
			"bi",
			"big",
			"bigger",
			"biggest",
			"bild", // German
			"bilder", // German
			"bill",
			"billed",
			"bills",
			"bit",
			"biz",
			"black",
			"blame",
			"blamed",
			"blames",
			"blaming",
			"blast",
			"blasted",
			"blend",
			"blended",
			"blending",
			"blends",
			"blind",
			"blindly",
			"blinded",
			"blinds",
			"blink",
			"blinked",
			"blinking",
			"block",
			"blog",
			"bloomberg",
			"blue",
			"bluesky",
			"bodies",
			"body",
			"book",
			"boost",
			"boosted",
			"boosting",
			"boosts",
			"bot",
			"both",
			"boy",
			"boys",
			"branch",
			"branches",
			"brand",
			"brands",
			"brave",
			"breach",
			"break",
			"breaking",
			"breakingnews",
			"breaks",
			"bright",
			"brighter",
			"brightest",
			"broken",
			"brown",
			"bsky",
			"build",
			"building",
			"business",
			"businesses",
			"but",
			"buy",
			"by",
			"bye",
			"ca", // TLD
			"caer", // Spanish
			"call",
			"calls",
			"came",
			"campaign",
			"campaigned",
			"campaigning",
			"campaigns",
			"can",
			"cancel",
			"canceled",
			"cancelled",
			"canceling",
			"cancelling",
			"cancels",
			"cannot",
			"capital",
			"capture",
			"captured",
			"captures",
			"card",
			"care",
			"carry",
			"case",
			"cases",
			"caso", // Spanish
			"casos", // Spanish
			"cat",
			"catch",
			"catching",
			"cats",
			"caught",
			"causal",
			"cause",
			"caused",
			"causing",
			"calendar",
			"ce", // French
			"center",
			"central",
			"certain",
			"certainly",
			"cesko", // Czech
			"ch", // TLD
			"challenge",
			"change",
			"changed",
			"changing",
			"channel",
			"channels",
			"channeled",
			"character",
			"characters",
			"chase",
			"chased",
			"chasing",
			"chat",
			"chateau", // French
			"chats",
			"chatting",
			"cherchez", // Spanish
			"chief",
			"chiefly",
			"choice",
			"choices",
			"choose",
			"chosen",
			"ciencia", // Spanish
			"cine", // French
			"circle",
			"cities",
			"citizens",
			"city",
			"civil",
			"claim",
			"claimed",
			"claiming",
			"claims",
			"class",
			"classic",
			"clear",
			"cleared",
			"clearing",
			"clears",
			"client",
			"clients",
			"club",
			"clubs",
			"cm", // TLD
			"cn", // TLD
			"cnn",
			"co", // TLD
			"coast",
			"coasted",
			"coasting",
			"coasts",
			"coin",
			"coins",
			"cold",
			"collaboration",
			"collapse",
			"collapsed",
			"collection",
			"color",
			"colored",
			"colorful",
			"coloring",
			"colors",
			"colour",
			"coloured",
			"colouring",
			"colours",
			"com", // TLD
			"come",
			"comment",
			"commentary",
			"commented",
			"commenting",
			"comments",
			"commercial",
			"commission",
			"commissioned",
			"commissions",
			"commit",
			"committed",
			"committing",
			"committee",
			"committees",
			"common",
			"communicate",
			"communicated",
			"communication",
			"communications",
			"community",
			"como", // Spanish
			"compact",
			"compacts",
			"companies",
			"company",
			"complaint",
			"complaints",
			"complete",
			"completed",
			"completely",
			"completes",
			"completing",
			"complex",
			"complicated",
			"compliance",
			"complicit",
			"component",
			"components",
			"computer",
			"con", // Spanish
			"concept",
			"concepts",
			"concern",
			"concerns",
			"concrete",
			"concretely",
			"conference",
			"conflict",
			"conflicted",
			"conflicts",
			"consequence",
			"consequences",
			"consider",
			"considered",
			"consolation",
			"console",
			"consoled",
			"consume",
			"consumed",
			"consumes",
			"consuming",
			"contain",
			"contains",
			"contemporary",
			"content",
			"contentious",
			"contents",
			"contrast",
			"contrasting",
			"contrasts",
			"control",
			"controversial",
			"controversy",
			"conversation",
			"conversations",
			"conversion",
			"convert",
			"converted",
			"converting",
			"cook",
			"cooked",
			"cooking",
			"cooks",
			"cool",
			"cooler",
			"coolest",
			"cooling",
			"corporate",
			"cost",
			"costs",
			"could",
			"course",
			"countries",
			"country",
			"couple",
			"cover",
			"coverage",
			"covered",
			"covers",
			"cr", // TLD (Costa Rica)
			"crap",
			"crappy",
			"craft",
			"crafts",
			"create",
			"created",
			"creates",
			"creating",
			"creation",
			"creative",
			"credit",
			"credited",
			"crediting",
			"credits",
			"critic",
			"critical",
			"criticism",
			"criticized",
			"criticizing",
			"critics",
			"critique",
			"cross",
			"cu", // Tagalog
			"cultural",
			"culture",
			"cum", // Latin
			"cup",
			"curious",
			"current",
			"currently",
			"curve",
			"curved",
			"curves",
			"curving",
			"customer",
			"customers",
			"cut",
			"cz", // TLD
			"daily",
			"danger",
			"dangerous",
			"dangerously",
			"dark",
			"darker",
			"darkest",
			"das", // German
			"data",
			"date",
			"dated",
			"daten", // German
			"dates",
			"dati", // French
			"david",
			"day",
			"daytime",
			"de", // German
			"deal",
			"dealed",
			"dealing",
			"deals",
			"dealt",
			"dear",
			"dearly",
			"death",
			"decency",
			"decent",
			"decently",
			"decide",
			"decides",
			"decision",
			"decisions",
			"decline",
			"declined",
			"declining",
			"deep",
			"defence",
			"defense",
			"degree",
			"deja", // French
			"del", // Spanish
			"delay",
			"delayed",
			"delaying",
			"delays",
			"delete",
			"deleted",
			"deletes",
			"deleting",
			"deliver",
			"delivered",
			"deliveries",
			"delivering",
			"delivery",
			"dem", // German
			"demand",
			"demanded",
			"demanding",
			"demands",
			"demo",
			"demolish",
			"den", // German
			"density",
			"depart",
			"department",
			"departments",
			"deploy",
			"deployed",
			"der", // German
			"design",
			"designed",
			"designing",
			"designs",
			"destination",
			"destinations",
			"destined",
			"destroy",
			"destroyed",
			"destroying",
			"destroys",
			"detail",
			"details",
			"development",
			"developments",
			"device",
			"devices",
			"die", // German
			"did",
			"diego",
			"digital",
			"dignify",
			"dignity",
			"dine",
			"dined",
			"dining",
			"dines",
			"dir", // German
			"direct",
			"directed",
			"directing",
			"direction",
			"directional",
			"directionally",
			"director",
			"directors",
			"directs",
			"dis", // Spanish
			"dislike",
			"disliked",
			"dislikes",
			"discourse",
			"discover",
			"discovered",
			"discovering",
			"discovers",
			"disgrace",
			"disgraceful",
			"disgracefully",
			"disgust",
			"disgusted",
			"disgusting",
			"disgusts",
			"display",
			"displayed",
			"displaying",
			"displays",
			"distraction",
			"distribute",
			"distributed",
			"distributes",
			"distributing",
			"distribution",
			"divide",
			"divided",
			"dividing",
			"division",
			"do",
			"dodge",
			"dodged",
			"dodging",
			"does",
			"dog",
			"dogs",
			"doing",
			"dollar",
			"dollars",
			"domestic",
			"don",
			"donald",
			"done",
			"donned",
			"door",
			"doors",
			"dos", // Spanish
			"dot",
			"double",
			"doubled",
			"doubles",
			"doubling",
			"doubt",
			"doubted",
			"doubts",
			"down",
			"download",
			"downloaded",
			"downloading",
			"downloads",
			"downtown",
			"dr",
			"drank",
			"draw",
			"drawn",
			"drift",
			"drifted",
			"drifts",
			"drink",
			"drinks",
			"drive",
			"driven",
			"driver",
			"drivers",
			"drove",
			"droves",
			"du", // German
			"each",
			"early",
			"earth",
			"ease",
			"easier",
			"east",
			"eastern",
			"easy",
			"eat",
			"eats",
			"eau", // French
			"economic",
			"economia", // Spanish
			"economie", // French
			"eeuu", // Spanish
			"edge",
			"effect",
			"effected",
			"effective",
			"effects",
			"efficiency",
			"efficient",
			"efficiently",
			"effort",
			"efforts",
			"edge",
			"edit",
			"edited",
			"editing",
			"edition",
			"editions",
			"editor",
			"editorial",
			"edits",
			"edu", // TLD
			"eight",
			"else",
			"em", // Spanish
			"email",
			"emerge",
			"emerged",
			"emergent",
			"emerging",
			"en",
			"enable",
			"enabled",
			"enables",
			"enabling",
			"encourage",
			"encouraged",
			"encourages",
			"encouraging",
			"encounter",
			"encountered",
			"encounters",
			"end",
			"ending",
			"ends",
			"enforce",
			"enforced",
			"enforcement",
			"enforcing",
			"eng", // "English" in some REST urls
			"engine",
			"english",
			"enjoy",
			"enough",
			"enquete",
			"enquire",
			"enquire",
			"enterprise",
			"enterprising",
			"entertain",
			"entertained",
			"entertains",
			"entertainment",
			"entitled",
			"entitles",
			"entitling",
			"entra", // Spanish
			"episode",
			"equipment",
			"era",
			"er", // German
			"erin", // name
			"es", // Spanish
			"escape",
			"estado", // Spanish
			"estados", // Spanish
			"et", // French
			"ete", // French
			"essential",
			"est", // Spanish
			"esta", // Spanish
			"etc",
			"euro",
			"europe",
			"european",
			"euros",
			"even",
			"event",
			"events",
			"evening",
			"evenings",
			"ever",
			"every",
			"everybody",
			"everyone",
			"everything",
			"everywhere",
			"evidence",
			"evil",
			"exact",
			"exactly",
			"exchange",
			"exchanged",
			"exchanges",
			"exclusive",
			"exclusively",
			"executive",
			"executives",
			"exist",
			"existed",
			"existing",
			"exists",
			"expansion",
			"expect",
			"expected",
			"expecting",
			"expects",
			"experience",
			"expert",
			"experts",
			"expertise",
			"explain",
			"explained",
			"explaining",
			"explains",
			"explore",
			"expression",
			"expressions",
			"ext", // TLD
			"extend",
			"extended",
			"extending",
			"extends",
			"extension",
			"extra",
			"extract",
			"extracted",
			"extracting",
			"extreme",
			"extremes",
			"eye",
			"eyed",
			"eyes",
			"eyeing",
			"face",
			"faced",
			"facebook",
			"faces",
			"facing",
			"fact",
			"factor",
			"factors",
			"facts",
			"fade",
			"faded",
			"fading",
			"fail",
			"failed",
			"failing",
			"fails",
			"failure",
			"fair",
			"fairer",
			"fairest",
			"fairly",
			"faith",
			"fall",
			"falling",
			"falls",
			"falsas", // Spanish
			"falsch", // German
			"false",
			"falso", // Spanish
			"familia", // Spanish
			"families",
			"family",
			"famous",
			"far",
			"farther",
			"farthest",
			"fast",
			"faster",
			"fastest",
			"feature",
			"featured",
			"features",
			"federal",
			"fee",
			"feed",
			"feel",
			"feels",
			"fell",
			"fellow",
			"felt",
			"female",
			"few",
			"fewer",
			"fewest",
			"fi",
			"field",
			"fields",
			"fight",
			"figure",
			"figured",
			"figures",
			"figuring",
			"file",
			"filed",
			"files",
			"filing",
			"filings",
			"fill",
			"filled",
			"fills",
			"fin", // French
			"final",
			"finally",
			"financial",
			"find",
			"finds",
			"fine",
			"finish",
			"finished",
			"fire",
			"fires",
			"first",
			"five",
			"flat",
			"flatten",
			"flew",
			"flies",
			"flight",
			"flights",
			"flipboard", // Fediverse server
			"floated",
			"floating",
			"floor",
			"floored",
			"floors",
			"fly",
			"flying",
			"focus",
			"focused",
			"focusing",
			"foi",
			"folk",
			"follow",
			"followed",
			"following",
			"follows",
			"food",
			"for",
			"force",
			"forced",
			"forces",
			"forcing",
			"foreign",
			"foreigner",
			"foreigners",
			"forget",
			"forgetting",
			"forgot",
			"form",
			"forth",
			"forum",
			"foto", // German
			"fotos",
			"found",
			"four",
			"fr", // TLD
			"frame",
			"framework",
			"framing",
			"frank",
			"free",
			"freedom",
			"freiheit", // German
			"french",
			"fresh",
			"freund", // German
			"friend",
			"friends",
			"fringe",
			"from",
			"front",
			"fuck",
			"fucked",
			"fucker",
			"fuckers",
			"fucking",
			"fucks",
			"full",
			"function",
			"functioned",
			"functions",
			"fund",
			"fundamental",
			"funded",
			"funding",
			"funds",
			"funny",
			"fur", // German
			"further",
			"furthermore",
			"future",
			"fyi",
			"garante", // Spanish
			"garden",
			"gardens",
			"gate",
			"gave",
			"gear",
			"gearing",
			"gen",
			"general",
			"generally",
			"generate",
			"genre",
			"genres",
			"geschichte", // German
			"get",
			"getting",
			"gets",
			"gif",
			"gift",
			"gifts",
			"girl",
			"girls",
			"give",
			"giving",
			"globe",
			"global",
			"glow",
			"glowing",
			"glows",
			"go",
			"goal",
			"god",
			"goes",
			"good",
			"goodbye",
			"goods",
			"got",
			"gotten",
			"gov", // TLD
			"govern",
			"government",
			"grad",
			"graphic",
			"gray",
			"great",
			"greater",
			"greatest",
			"greatly",
			"green",
			"grey",
			"grip",
			"gripe",
			"gripped",
			"grips",
			"group",
			"groups",
			"gross",
			"grow",
			"growing",
			"grown",
			"grows",
			"growth",
			"gruene", // German
			"grune", // German
			"grunen", // German
			"guarantee",
			"guaranteed",
			"guarantees",
			"guardian",
			"guide",
			"guy",
			"ha",
			"haber", // Spanish
			"hackernews",
			"had",
			"haha",
			"hallo",
			"hand",
			"handed",
			"handing",
			"hands",
			"hard",
			"harder",
			"hardest",
			"hardly",
			"has",
			"hat", // German
			"he",
			"head",
			"headline",
			"headlines",
			"health",
			"hear",
			"heard",
			"hearing",
			"heart",
			"heat",
			"heavier",
			"heaviest",
			"heavily",
			"heaviness",
			"heavy",
			"heise", // German
			"heisse", // German
			"heiße", // German
			"hell",
			"hello",
			"help",
			"her",
			"here",
			"herself",
			"hi",
			"hid",
			"hidden",
			"hide",
			"hides",
			"hiding",
			"hier", // German
			"high",
			"higher",
			"highest",
			"highlight",
			"highlighted",
			"highlighting",
			"highlights",
			"highly",
			"him",
			"himself",
			"hip",
			"histoire", // French
			"historia", // Spanish
			"historic",
			"history",
			"his",
			"hit",
			"hits",
			"hk", // TLD
			"home",
			"homepage",
			"homes",
			"hope",
			"hoped",
			"hopes",
			"hoping",
			"hot",
			"how",
			"however",
			"hour",
			"hours",
			"house",
			"houses",
			"htm",
			"html",
			"http",
			"https",
			"huge",
			"hugely",
			"huh",
			"human",
			"humanity",
			"humanly",
			"humans",
			"ia", // Italian / Romanian
			"id",
			"idea",
			"ideal",
			"ideals",
			"ideas",
			"if",
			"identity",
			"il", // Italian / French
			"illegally",
			"im",
			"image",
			"imagery",
			"images",
			"imagine",
			"imagined",
			"imagines",
			"imagining",
			"immediate",
			"immediately",
			"impact",
			"impacted",
			"impacts",
			"important",
			"importantly",
			"impress",
			"impressive",
			"in",
			"inbox",
			"inc",
			"incident",
			"incidental",
			"incidentally",
			"incidents",
			"include",
			"included",
			"includes",
			"including",
			"inclusion",
			"independent",
			"independently",
			"index",
			"industry",
			"influence",
			"influenced",
			"influencing",
			"info",
			"information",
			"infosec", // infosec.exchange is a big server
			"insight",
			"insightful",
			"insights",
			"instagram",
			"install",
			"installed",
			"installation",
			"installations",
			"instance",
			"institute",
			"institution",
			"institutional",
			"institutions",
			"integration",
			"intelligence",
			"intelligent",
			"interest",
			"interested",
			"interesting",
			"interestingly",
			"interests",
			"interior",
			"internacional",
			"internal",
			"international",
			"internet",
			"into",
			"intro",
			"introduce",
			"introduced",
			"introducing",
			"introduction",
			"invest",
			"invested",
			"investing",
			"invests",
			"involve",
			"involved",
			"involves",
			"involving",
			"io", // TLD
			"is",
			"isolate",
			"isolated",
			"issue",
			"issued",
			"issues",
			"issuing",
			"it",
			"its",
			"itself",
			"ja", // German
			"je", // French
			"jeunes", // French
			"jeff",
			"jeffrey",
			"job",
			"joe",
			"join",
			"joined",
			"joining",
			"joins",
			"joint",
			"jointly",
			"jose",
			"journal",
			"jp",
			"jpeg",
			"jpg",
			"jr",
			"just",
			"justin",
			"keep",
			"keeps",
			"key",
			"keys",
			"ki", // Spanish?
			"kind",
			"kinds",
			"knew",
			"know",
			"knowing",
			"knowledge",
			"kultur", // German
			"la", // French
			"label",
			"labeled",
			"labeling",
			"labelling",
			"labels",
			"lack",
			"lacked",
			"lacking",
			"lacks",
			"lake",
			"land",
			"landscape",
			"large",
			"larger",
			"largest",
			"las", // Spanish
			"last",
			"lasts",
			"late",
			"later",
			"latest",
			"lay",
			"lays",
			"le", // French
			"led",
			"lead",
			"leader",
			"leaders",
			"leadership",
			"leading",
			"leads",
			"leak",
			"leaked",
			"leaks",
			"leaking",
			"learn",
			"learns",
			"learning",
			"least",
			"leave",
			"leaves",
			"leaving",
			"lee",
			"left",
			"leg",
			"legacy",
			"legacies",
			"legs",
			"legal",
			"leisure",
			// "lemonde",        // French
			"les", // French
			"less",
			"lesser",
			"let",
			"level",
			"levels",
			"libre", // Spanish
			"lie",
			"lies",
			"life",
			"lifestyle",
			"lifetime",
			"light",
			"like",
			"liked",
			"likes",
			"likely",
			"line",
			"lined",
			"lines",
			"link",
			"linked",
			"linking",
			"links",
			"list",
			"listed",
			"listen",
			"listened",
			"listening",
			"listens",
			"listing",
			"lists",
			"little",
			"live",
			"lived",
			"lives",
			"living",
			"loan",
			"loaned",
			"loans",
			"local",
			"location",
			"locations",
			"lose",
			"loses",
			"losing",
			"loss",
			"lost",
			"lot",
			"local",
			"locally",
			"log",
			"logging",
			"logic",
			"logical",
			"long",
			"look",
			"looked",
			"looking",
			"looks",
			"los",
			"love",
			"loved",
			"loves",
			"low",
			"lower",
			"lowest",
			"lustig",
			"ma",
			"macht", // German
			"mad",
			"made",
			"magazine",
			"magazines",
			"mail",
			"main",
			"mainly",
			"major",
			"majority",
			"majorly",
			"make",
			"makes",
			"making",
			"mal", // Spanish
			"male",
			"man",
			"manipulate",
			"manipulated",
			"manipulating",
			"manner",
			"many",
			"map",
			"mapping",
			"maps",
			"mark",
			"marked",
			"marker",
			"market",
			"marketing",
			"marks",
			"mas", // Spanish
			"mass",
			"master",
			"mastered",
			"mastodon",
			"match",
			"matched",
			"matches",
			"matching",
			"material",
			"materials",
			"matter",
			"max",
			"maximum",
			"may",
			"maybe",
			"me",
			"mean",
			"meaning",
			"meaningful",
			"meaningfully",
			"meaningless",
			"means",
			"meant",
			"media", // TLD
			"medias",
			"medien", // German
			"medium",
			"meduza",
			"meer", // Dutch
			"meet",
			"meeting",
			"meetings",
			"melt",
			"melted",
			"melting",
			"member",
			"members",
			"membership",
			"memories",
			"memory",
			"men",
			"mensch", // German
			"menschen", // German
			"mention",
			"mentioned",
			"mentions",
			"mere",
			"merely",
			"message",
			"messages",
			"messaging",
			"met",
			"metro",
			"middle",
			"mientras", // Spanish
			"million",
			"millions",
			"min",
			"mind",
			"mine",
			"minimal",
			"minimally",
			"minimum",
			"minister",
			"mins",
			"minute",
			"minutes",
			"mit", // German
			"mix",
			"mixed",
			"mixes",
			"mixing",
			"mode",
			"model",
			"models",
			"modern",
			"monde", // French
			"money",
			"montag", // German
			"month",
			"months",
			"more",
			"moreover",
			"morning",
			"most",
			"mostly",
			"mother",
			"move",
			"moved",
			"movement",
			"moves",
			"moving",
			"mr",
			"mrs",
			"ms",
			"mstdn",
			"mt", // Mountain
			"much",
			"mucho", // Spanish
			"mundo", // Spanish
			"must",
			"my",
			"na", // Spanish
			"nachrichten", // German
			"name",
			"named",
			"names",
			"naming",
			"nation",
			"national",
			"nationality",
			"nations",
			"natural",
			"ne", // Spanish
			"near",
			"nearby",
			"nearer",
			"nears",
			"nearly",
			"negative",
			"negotiate",
			"negotiated",
			"negotiates",
			"negotiating",
			"neighbor",
			"neighboring",
			"neighbors",
			"neither",
			"net",
			"network",
			"networks",
			"neutral",
			"never",
			"nevertheless",
			"new",
			"newer",
			"newest",
			"newly",
			"news",
			"next",
			"ngated",
			"nice",
			"nicely",
			"nicer",
			"nicest",
			"niet", // Dutch
			"nieuws", // Dutch
			"nil",
			"night",
			"nine",
			"nl", // TLD
			"no",
			"nobody",
			"noir", // French
			"noire", // French
			"non",
			"none",
			"nonsense",
			"nope",
			"nor",
			"nord", // French
			"north",
			"northern",
			"nos", // French
			"not",
			"note",
			"noted",
			"notes",
			"nothing",
			"notice",
			"noticeable",
			"notices",
			"noticed",
			"noticias",
			"noting",
			"notizie", // Italian
			"novel",
			"novembre", // Italian
			"novita", // Italian
			"now",
			"number",
			"nytimes",
			"nz", // TLD
			"oc",
			"odd",
			"oder", // German
			"of",
			"off",
			"offensive",
			"office",
			"offices",
			"official",
			"officials",
			"offline",
			"oft",
			"often",
			"oh",
			"ok",
			"okay",
			"ol", // German
			"old",
			"older",
			"oldest",
			"omg",
			"on",
			"once",
			"one",
			"online",
			"ooh",
			"oops",
			"open",
			"opinion",
			"opinions",
			"opportunities",
			"opportunity",
			"oppose",
			"opposed",
			"opposing",
			"opt",
			"optimal",
			"optimize",
			"optimized",
			"optimum",
			"options",
			"or",
			"orange",
			"org",
			"organic",
			"organically",
			"organisation",
			"organisations",
			"organization",
			"organizations",
			"organize",
			"organized",
			"organizes",
			"organizing",
			"origin",
			"origins",
			"original",
			"originale", // French
			"originals",
			"originally",
			"other",
			"others",
			"our",
			"out",
			"outcome",
			"outcomes",
			"outside",
			"over",
			"overall",
			"own",
			"owner",
			"pa",
			"pace",
			"pack",
			"package",
			"packages",
			"packed",
			"packs",
			"paid",
			"pais", // Spanish
			"pan",
			"panel",
			"paper",
			"papier", // French
			"papieros", // French
			"papiers", // French
			"park",
			"parked",
			"parking",
			"part",
			"partly",
			"participate",
			"participated",
			"participates",
			"participating",
			"participation",
			"participations",
			"participatory",
			"particular",
			"particularly",
			"parties",
			"partisan",
			"partner",
			"partners",
			"partnership",
			"partnerships",
			"parts",
			"party",
			"pas", // French
			"pasado", // Spanish
			"pass",
			"passed",
			"passion",
			"past",
			"pat",
			"patch",
			"path",
			"paths",
			"pattern",
			"patterns",
			"paul",
			"pay",
			"payment",
			"pays",
			"peaceful",
			"people",
			"peoples",
			"per",
			"perfect",
			"perfected",
			"perfectly",
			"performance",
			"performances",
			"permission",
			"person",
			"personal",
			"personally",
			"perspective",
			"perspectives",
			"pet",
			"pete",
			"peter",
			"petit",
			"petite",
			"photo",
			"photograph",
			"photos",
			"physical",
			"pic",
			"pick",
			"picked",
			"picking",
			"picks",
			"pics",
			"picture",
			"pictures",
			"piece",
			"pierce",
			"pierced",
			"pierces",
			"piercing",
			"pink",
			"pixelfed", // pixelfed.social
			"pl",
			"place",
			"placement",
			"placements",
			"places",
			"placed",
			"plan",
			"planet",
			"planned",
			"planning",
			"plans",
			"plant",
			"planted",
			"platform",
			"platforms",
			"play",
			"playbook",
			"played",
			"player",
			"players",
			"playing",
			"plays",
			"please",
			"pleased",
			"pleasing",
			"plot",
			"pluralistic", // TODO: the regex should probably exclude @account mentions...
			"plus",
			"pm",
			"poetic",
			"point",
			"pointed",
			"points",
			"pol",
			"pole",
			"poles",
			"policies",
			"policy",
			"politica", // Spanish
			"political",
			"politicas", // Spanish
			"politics",
			"politik",
			"politiken", // Danish
			"politique", // French
			"politiques", // French
			"politisch", // German
			"polititian",
			"poll",
			"pop",
			"popped",
			"popping",
			"pops",
			"popular",
			"population",
			"popularly",
			"por", // Spanish
			"portfolio",
			"pose",
			"posed",
			"poses",
			"posing",
			"positive",
			"possibility",
			"possibilities",
			"possible",
			"possibly",
			"post",
			"posted",
			"posting",
			"posts",
			"pour",
			"power",
			"powered",
			"powering",
			"powers",
			"practice",
			"practices",
			"pre",
			"precise",
			"precisely",
			"precision",
			"predict",
			"predicted",
			"predicting",
			"prediction",
			"predicts",
			"president",
			"presidente", // Spanish
			"presidents",
			"press",
			"presse", // German
			"pretty",
			"prevent",
			"preventable",
			"prevented",
			"preventing",
			"prevents",
			"previous",
			"previously",
			"principle",
			"principles",
			"print",
			"printed",
			"private",
			"privately",
			"privilege",
			"pro",
			"profile",
			"profiles",
			"problem",
			"problematic",
			"problemo", // Spanish
			"problems",
			"probably",
			"procedure",
			"procedures",
			"proceso", // Spanish
			"process",
			"processed",
			"processes",
			"processing",
			"produce",
			"product",
			"production",
			"products",
			"programs",
			"progress",
			"progressed",
			"progressing",
			"progression",
			"progressions",
			"project",
			"projected",
			"projecting",
			"projects",
			"prominent",
			"promise",
			"promises",
			"promo",
			"promote",
			"promoted",
			"promotes",
			"promoting",
			"promotion",
			"promotions",
			"prompted",
			"prompting",
			"proper",
			"properly",
			"property",
			"protect",
			"protected",
			"protecting",
			"protection",
			"protects",
			"provide",
			"provided",
			"provides",
			"ps",
			"pub", // TLD
			"public",
			"publicly",
			"publish",
			"published",
			"publishing",
			"pull",
			"pulling",
			"pulls",
			"pump",
			"pumped",
			"pumping",
			"pumps",
			"push",
			"pushed",
			"pushes",
			"put",
			"puts",
			"quality",
			"que", // Spanish
			"question",
			"questioned",
			"questions",
			"quick",
			"quickly",
			"quite",
			"quote",
			"quoted",
			"quotes",
			"quoting",
			"race",
			"raced",
			"racing",
			"raise",
			"raised",
			"raises",
			"raising",
			"ran",
			"random",
			"range",
			"ranges",
			"ranging",
			"rank",
			"ranking",
			"rankings",
			"rat",
			"rate",
			"rates",
			"raw",
			"ra",
			"re",
			"reach",
			"reached",
			"reaches",
			"reaching",
			"reaction",
			"reactions",
			"read",
			"reader",
			"readers",
			"reads",
			"reading",
			"ready",
			"readying",
			"real",
			"reality",
			"realize",
			"realized",
			"realizes",
			"realizing",
			"really",
			"reason",
			"reasoned",
			"reasoning",
			"reasons",
			"receive",
			"received",
			"receives",
			"receiving",
			"recent",
			"recently",
			"rechts", // German
			"recognize",
			"recognized",
			"recognizing",
			"recognizes",
			"record",
			"recorded",
			"recording",
			"recordings",
			"records",
			"recovery",
			"red",
			"redo",
			"reduce",
			"reduced",
			"reduces",
			"reducing",
			"reduction",
			"reductions",
			"reference",
			"referenced",
			"referencing",
			"reflect",
			"reflected",
			"reflecting",
			"reflects",
			"region",
			"regional",
			"regions",
			"rejoin",
			"rejoined",
			"relate",
			"related",
			"relates",
			"relating",
			"release",
			"released",
			"releases",
			"releasing",
			"relevant",
			"relax",
			"relaxed",
			"relaxing",
			"reliable",
			"relief",
			"remain",
			"remaining",
			"remains",
			"remember",
			"remembered",
			"remembering",
			"remote",
			"remotely",
			"rep",
			"repair",
			"repaired",
			"repairing",
			"repeat",
			"repeated",
			"repeating",
			"repeats",
			"replace",
			"replaced",
			"replaces",
			"replacing",
			"report",
			"reporter",
			"reporting",
			"reports",
			"repost",
			"reposted",
			"reposting",
			"reputation",
			"reputations",
			"require",
			"required",
			"requires",
			"requisite",
			"reserve",
			"reset",
			"resets",
			"resign",
			"resigned",
			"resigning",
			"resigns",
			"resilience",
			"resist",
			"respect",
			"respected",
			"respecting",
			"respects",
			"respond",
			"responds",
			"response",
			"responses",
			"responsibilities",
			"responsibility",
			"responsible",
			"responsibly",
			"rest",
			"rests",
			"restore",
			"restored",
			"restores",
			"restoring",
			"result",
			"resulted",
			"results",
			"ret", // "retired"
			"retail",
			"rete", // Italian
			"return",
			"returned",
			"returning",
			"returns",
			"reuse",
			"reused",
			"reuses",
			"reusing",
			"reveal",
			"revealed",
			"revealing",
			"reveals",
			"revelation",
			"revelations",
			"revenue",
			"revenues",
			"review",
			"reviewed",
			"reviewing",
			"reviews",
			"rich",
			"right",
			"rip",
			"ripe",
			"ripped",
			"ripping",
			"rise",
			"risk",
			"risks",
			"ro", // Romanian TLD
			"rob", // Name
			"robert", // Name
			"road",
			"rocks",
			"roll",
			"rolled",
			"rolling",
			"rolls",
			"room",
			"rooms",
			"rose",
			"rouge", // French
			"round",
			"rounds",
			"rss",
			"rule",
			"ruled",
			"rules",
			"run",
			"running",
			"rural",
			"rush",
			"rushed",
			"rushes",
			"rushing",
			"sa",
			"sad",
			"safety",
			"said",
			"sale",
			"sales",
			"sam",
			"same",
			"san",
			"sans", // French
			"save",
			"saved",
			"saves",
			"saving",
			"say",
			"says",
			"scale",
			"scan",
			"scanned",
			"scans",
			"scare",
			"scared",
			"scares",
			"scaring",
			"scary",
			"scene",
			"scenic",
			"scenes",
			"scheme",
			"screenshot", // Used in a lot of alt text
			"se", // Spanish
			"sean", // Name
			"search",
			"searched",
			"searches",
			"searching",
			"season",
			"seat",
			"second",
			"seconds",
			"secret",
			"section",
			"sections",
			"sector",
			"sectors",
			"seguranca", // Spanish
			"securite", // French
			"security",
			"see",
			"seen",
			"seeking",
			"seems",
			"seen",
			"sees",
			"seguridad", // Spanish
			"self",
			"sell",
			"selling",
			"sells",
			"sen",
			"send",
			"sense",
			"sensed",
			"sensing",
			"sent",
			"sentence",
			"septiembre", // Spanish
			"serial",
			"series",
			"serious",
			"seriously",
			"service",
			"services",
			"session",
			"set",
			"seth",
			"sets",
			"setting",
			"settings",
			"setup",
			"seven",
			"several",
			"severe",
			"sex",
			"shadow",
			"shadows",
			"shadowy",
			"shared",
			"sharing",
			"sharp",
			"sharper",
			"shape",
			"share",
			"she",
			"shit",
			"shitty",
			"shittier",
			"shop",
			"shopped",
			"shopping",
			"short",
			"shorter",
			"shortest",
			"shorts", // YouTube shorts
			"shot",
			"should",
			"show",
			"showed",
			"showing",
			"shown",
			"shows",
			"si", // Spanish
			"side",
			"sides",
			"sign",
			"signed",
			"signing",
			"signs",
			"silly",
			"similar",
			"similarly",
			"simple",
			"simpler",
			"simplest",
			"simplicity",
			"simply",
			"since",
			"sit",
			"sits",
			"situation",
			"situations",
			"six",
			"size",
			"sized",
			"sizes",
			"sizing",
			"sk", // TLD
			"skill",
			"skilled",
			"skills",
			"slightly",
			"slow",
			"slower",
			"slowest",
			"small",
			"smaller",
			"smallest",
			"smart",
			"sn", // TLD
			"snap",
			"snaps",
			"snapped",
			"snapping",
			"so",
			"sobre", // Spanish
			"social",
			"society",
			"soft",
			"softer",
			"softest",
			"softly",
			"solution",
			"solutions",
			"solve",
			"solved",
			"solves",
			"solving",
			"some",
			"somebody",
			"someone",
			"sometime",
			"something",
			"soon",
			"sooner",
			"soonest",
			"soul",
			"sound",
			"sounded",
			"sounding",
			"sounds",
			"source",
			"sourced",
			"sources",
			"sourcing",
			"south",
			"southern",
			"space",
			"spass", // German
			"speak",
			"speaking",
			"speaks",
			"special",
			"specialization",
			"specific",
			"specifics",
			"specifically",
			"speculation",
			"speech",
			"speeches",
			"speed",
			"spend",
			"spende", // German
			"spending",
			"spends",
			"spent",
			"spiel", // German
			"spielzug", // German
			"sphere",
			"spheres",
			"spin",
			"spins",
			"spoke",
			"spot",
			"spotted",
			"spring",
			"spun",
			"st",
			"stadt", // German
			"stand",
			"standing",
			"stands",
			"standard",
			"standards",
			"star",
			"stars",
			"start",
			"started",
			"starts",
			"state",
			"states",
			"status",
			"stem",
			"stemmed",
			"stemming",
			"stems",
			"step",
			"stepped",
			"steps",
			"stepping",
			"steve",
			"stick",
			"sticking",
			"sticks",
			"still",
			"stillness",
			"stock",
			"stone",
			"stood",
			"stop",
			"stopped",
			"stopping",
			"stops",
			"store",
			"stories",
			"story",
			"strange",
			"strategie", // French
			"strategies",
			"strategy",
			"stream",
			"streamed",
			"streaming",
			"street",
			"streets",
			"strikes",
			"strength",
			"strengthen",
			"strengthened",
			"strengthening",
			"strengths",
			"strong",
			"stronger",
			"strongest",
			"stuck",
			"study",
			"studying",
			"studied",
			"studies",
			"stuff",
			"stupid",
			"sturm", // German
			"style",
			"styled",
			"styles",
			"subject",
			"subjects",
			"subj", // German
			"su",
			"substack",
			"such",
			"success",
			"successes",
			"successful",
			"sudden",
			"suddenly",
			"summer",
			"super",
			"superb",
			"superbly",
			"supplied",
			"supplier",
			"suppliers",
			"supplies",
			"supply",
			"support",
			"supported",
			"supporter",
			"supporters",
			"supporting",
			"supports",
			"sur", // French
			"sure",
			"surely",
			"swap",
			"sweet",
			"sweeter",
			"sweetest",
			"sweetly",
			"switch",
			"switched",
			"switches",
			"switching",
			"system",
			"systems",
			"tag",
			"tags",
			"take",
			"takes",
			"taken",
			"takeover",
			"takeovers",
			"taking",
			"talk",
			"talked",
			"talking",
			"talks",
			"tall",
			"taller",
			"tan",
			"tap",
			"tapped",
			"tapping",
			"taps",
			"tarde", // Spanish
			"target",
			"targeted",
			"targeting",
			"targets",
			"task",
			"team",
			"teamed",
			"teaming",
			"teams",
			"tech",
			"template",
			"ten",
			"tend",
			"tends",
			"test",
			"testing",
			"text",
			"than",
			"thank",
			"thanked",
			"thanks",
			"that",
			"the",
			"theguardian",
			"them",
			"theme",
			"themes",
			"themselves",
			"then",
			"their",
			"there",
			"these",
			"they",
			"thing",
			"things",
			"think",
			"thinking",
			"thinks",
			"this",
			"those",
			"thought",
			"thoughts",
			"thousand",
			"thousands",
			"threads",
			"three",
			"through",
			"throughout",
			"thumbnail",
			"ticket",
			"tie",
			"ties",
			"til",
			"tilt",
			"tilted",
			"tilts",
			"tim",
			"time",
			"times",
			"tiny",
			"tip",
			"tipped",
			"tipping",
			"tips",
			"title",
			"titled",
			"titles",
			"to",
			"today",
			"together",
			"tom",
			"ton",
			"tonne",
			"tonnes",
			"tons",
			"too",
			"tool",
			"tools",
			"top",
			"topstories", // Someone's dumb hashtag
			"total",
			"touch",
			"tough",
			"tougher",
			"toughest",
			"town",
			"track",
			"tracked",
			"tracking",
			"trade",
			"traded",
			"trades",
			"trading",
			"tradition",
			"traditional",
			"traditions",
			"trail",
			"train",
			"training",
			"transfer",
			"transferred",
			"transferring",
			"transfers",
			"transformation",
			"transformations",
			"transformative",
			"transport",
			"transported",
			"transporting",
			"transports",
			"trap",
			"trapped",
			"traps",
			"travel",
			"treat",
			"treats",
			"trending",
			"tried",
			"trip",
			"true",
			"trust",
			"trusted",
			"trusts",
			"trustworthy",
			"truth",
			"try",
			"trying",
			"ts", // TLD
			"tue", // German
			"turn",
			"turned",
			"turning",
			"turns",
			"tv",
			"two",
			"tying",
			"type",
			"types",
			"typical",
			"typically",
			"ua",
			"uk",
			"un",
			"una", // Spanish
			"uncertain",
			"uncertainty",
			"und", // German
			"under",
			"understand",
			"understanding",
			"understands",
			"understood",
			"unfair",
			"unfairly",
			"unfinished",
			"unique",
			"uniquely",
			"united",
			"unity",
			"unknown",
			"une", // French
			"unless",
			"uno", // Italian
			"uns", // German
			"until",
			"untrustworthy",
			"unusual",
			"unusually",
			"up",
			"update",
			"updated",
			"updates",
			"updating",
			"upon",
			"urban",
			"us",
			"usa",
			"use",
			"used",
			"user",
			"users",
			"uses",
			"using",
			"usual",
			"usually",
			"va", // Spanish
			"valley",
			"valleys",
			"value",
			"valued",
			"values",
			"varieties",
			"variety",
			"various",
			"variously",
			"vast",
			"vastly",
			"ve", // French
			"vehicle",
			"ver", // German
			"verified",
			"verify",
			"version",
			"versions",
			"very",
			"via",
			"vibrant",
			"victim",
			"video",
			"videos",
			"view",
			"views",
			"viewed",
			"viewing",
			"visit",
			"visited",
			"visiting",
			"visitor",
			"visitors",
			"visits",
			"visual",
			"voice",
			"voices",
			"von",
			"vuelta", // Spanish
			"vs",
			"wahrun", // German
			"wait",
			"waiting",
			"waits",
			"wall",
			"walk",
			"walked",
			"walking",
			"walks",
			"want",
			"wanted",
			"wanting",
			"wants",
			"warm",
			"warn",
			"warned",
			"was",
			"wash",
			"washed",
			"washing",
			"washingtonpost",
			"waste",
			"wasted",
			"wasting",
			"watch",
			"watched",
			"watching",
			"water",
			"wave",
			"waved",
			"waver",
			"waves",
			"way",
			"we",
			"weak",
			"weaker",
			"weakest",
			"wear",
			"wearing",
			"wears",
			"web",
			"website",
			"websites",
			"week",
			"weekend",
			"weekends",
			"weekly",
			"weeks",
			"weigh",
			"weighing",
			"weird",
			"weirder",
			"weirdest",
			"weirdly",
			"weirdness",
			"welcome",
			"well",
			"welt", // German
			"weltraum", // German
			"wenn", // German
			"went",
			"were",
			"west",
			"western",
			"wetter", // German
			"what",
			"when",
			"where",
			"whether",
			"which",
			"while",
			"white",
			"who",
			"whole",
			"whom",
			"whose",
			"why",
			"wide",
			"wider",
			"widest",
			"wild",
			"will",
			"willing",
			"win",
			"window",
			"winning",
			"winter",
			"wip",
			"wird", // German
			"wirtschaft", // German
			"wissen", // German
			"with",
			"within",
			"without",
			"wochenende", // German
			"woman",
			"women",
			"won",
			"wonder",
			"wondered",
			"wondering",
			"wonders",
			"word",
			"wording",
			"words",
			"wore",
			"work",
			"worked",
			"worker",
			"workers",
			"working",
			"works",
			"workshop",
			"world",
			"worldnews",
			"worldview",
			"worried",
			"worry",
			"worrying",
			"worse",
			"worst",
			"would",
			"wow",
			"write",
			"writes",
			"writing",
			"wrong",
			"wsj",
			"www",
			"ycombinator",
			"ya",
			"yahoo",
			"yay",
			"yea",
			"yeah",
			"year",
			"years",
			"yeh",
			"yellow",
			"yep",
			"yes",
			"yesterday",
			"yet",
			"yo",
			"yonhapinfomax",
			"york",
			"you",
			"young",
			"younger",
			"youngest",
			"your",
			"yourself",
			"yourselves",
			"youtube",
			"za", // South Africa TLD
			"zach", // Name
			"ze",
			"zeit", // German
			"zh", // Chinese
			"zu", // German
			"zukunft", // German
		]),
	};

	trending = {
		daysToCountTrendingData: 3, // Look at this many days of user counts when assessing trending data
		tags: {
			invalidTags: [
				// Tags that are too generic to be considered trending
				"government",
				"news",
				"photography",
			],
			maxPosts: 200, // Max number of posts with trending tags to push into the user's feed
			numTagsPerServer: 20, // How many trending tags to pull from each server (Mastodon default is 10)
			numTags: 20, // How many trending tags to use after ranking their popularity
			numPostsPerTag: 15, // How many posts to pull for each trending tag
		},
		posts: {
			numTrendingPostsPerServer: 30, // How many trending posts to pull per server // TODO: unused?
		},
	};

	/** Construct a new {@linkcode Config} instance, validate it, and logs the validated config. */
	constructor() {
		this.validate(this);
		console.debug(`${LOG_PREFIX} validated:`, this);
	}

	/**
	 * Computes the minimum value of {@linkcode minutesUntilStale} for all {@linkcode enums:FediverseCacheKey}
	 * values. Warns if any required keys are missing a value.
	 * @returns {number} The minimum minutes until trending data is considered stale, or 60 if not all keys are configured.
	 */
	minTrendingMinutesUntilStale(): number {
		const trendStalenesses = Object.values(FediverseCacheKey)
			.map((k) => this.api.data[k]?.minutesUntilStale)
			.filter(Boolean);

		if (trendStalenesses.length != Object.values(FediverseCacheKey).length) {
			console.warn(
				`${LOG_PREFIX} Not all FediverseCacheKey values have minutesUntilStale configured!`,
			);
			return 60;
		} else {
			return Math.min(...(trendStalenesses as number[]));
		}
	}

	/**
	 * Sets the locale, language, and country for the application if supported.
	 * Falls back to defaults if the locale is invalid or unsupported.
	 * @param {string} [locale] - The locale string (e.g. "en-CA").
	 */
	setLocale(locale?: string): void {
		locale ??= DEFAULT_LOCALE;

		if (!LOCALE_REGEX.test(locale)) {
			console.warn(
				`${LOG_PREFIX} Invalid locale "${locale}", using default "${DEFAULT_LOCALE}"`,
			);
			return;
		}

		this.locale.locale = locale;
		const [language, country] = locale.split("-");
		this.locale.country = country || DEFAULT_COUNTRY;

		if (language) {
			this.locale.language = language;
		}
	}

	/**
	 * Validates config values for correctness (e.g. checks for NaN or empty strings).
	 * @private
	 * @param {ConfigType | object} [cfg] - The config object or sub-object to validate.
	 * @throws {Error} If any config value is invalid.
	 */
	private validate(cfg?: ConfigType | object): void {
		if (!cfg) {
			if (
				!this.api.data[CacheKey.HOME_TIMELINE_POSTS]?.lookbackForUpdatesMinutes
			) {
				throw new Error(
					`${LOG_PREFIX} HOME_TIMELINE_POSTS lookbackForUpdatesMinutes is not set!`,
				);
			}
		}

		// Check that all the values are valid
		Object.entries(cfg || this).forEach(([key, value]) => {
			if (typeof value === "object") {
				this.validate(value);
			} else if (typeof value == "number" && isNaN(value)) {
				const msg = `value at ${key} is NaN`;
				console.error(`${LOG_PREFIX} ${msg}`);
				throw new Error(msg);
			} else if (typeof value == "string" && value.length == 0) {
				const msg = `value at ${key} is empty string`;
				console.error(`${LOG_PREFIX} ${msg}`);
				throw new Error(msg);
			}
		});
	}
}

const config = new Config();

// Quick load mode settings
if (isQuickMode) {
	console.debug(`${LOG_PREFIX} QUICK_MODE enabled, applying debug settings...`);
	config.api.data[CacheKey.HOME_TIMELINE_POSTS]!.initialMaxRecords = 240;
	config.api.data[CacheKey.HOME_TIMELINE_POSTS]!.lookbackForUpdatesMinutes = 10;
	config.api.backgroundLoadIntervalMinutes = SECONDS_IN_HOUR;
	config.favouritedTags.numTags = 5;
	config.posts.maxTimelineLength = 1_500;
	config.participatedTags.numTags = 10;
	config.trending.tags.numTags = 10;
}

// Debug mode settings
if (isDebugMode) {
	console.debug(
		`${LOG_PREFIX} FEDIALGO_DEBUG mode enabled, applying debug settings...`,
	);
	config.api.data[CacheKey.FOLLOWED_ACCOUNTS]!.initialMaxRecords = 160;
	config.api.data[CacheKey.FOLLOWED_TAGS]!.minutesUntilStale = 60;
	config.api.data[CacheKey.FOLLOWERS]!.initialMaxRecords = 320;
	config.api.data[CacheKey.NOTIFICATIONS]!.minutesUntilStale = 10;
	config.api.data[CacheKey.RECENT_USER_POSTS]!.minutesUntilStale = 5;
	config.api.backgroundLoadIntervalMinutes = 5;
	config.api.maxRecordsForFeatureScoring = 2_500;
	config.posts.saveChangesIntervalSeconds = 15;
}

// Heavy load test settings
if (isLoadTest) {
	console.debug(
		`${LOG_PREFIX} LOAD_TEST mode enabled, applying debug settings...`,
	);
	config.api.data[CacheKey.HOME_TIMELINE_POSTS]!.initialMaxRecords = 2_500;
	config.posts.maxTimelineLength = 5_000;
	config.api.maxRecordsForFeatureScoring = 15_000;
	config.participatedTags.maxPosts = 500;
	config.participatedTags.numTags = 50;
	config.participatedTags.numPostsPerTag = 10;
	config.trending.tags.maxPosts = 1_000;
	config.trending.tags.numTags = 40;
}

export { config };
